### ISSUE TITLE
Repository standardization

### ISSUE THREAD

**Issue by luxonauta** [dracula/starship#1]
Hi @b3vis, we need to adjust a few things first to move forward, ok? ✨

First, we need to update the screenshot! Can you make a single capture at the **closest possible resolution** to **1728x1117**?

And remove that capture information just below the current [readme](https://github.com/dracula/starship/blob/master/README.md)?

I ask for these changes to standardize with the other repositories, see [an example](https://github.com/dracula/notepad-plus-plus); this is important because it helps other possible users who would like to contribute too! 😁

Let me know if something is not possible or if you have any doubts! 🙂

**Comment by grantbevis** [comment]
Hi @luxonauta - No worries I'll get a new screenshot and remove the information as requested!

**Comment by grantbevis** [comment]
@luxonauta - This has been completed under https://github.com/dracula/starship/pull/2

**Comment by luxonauta** [comment]
Cool, I've done the following steps! 😁
Once [the PR on draculatheme.com](https://github.com/dracula/draculatheme.com/pull/148) is accepted, the project will be available on the website! 🚀
